import Head from 'next/head'
import { useState } from 'react';
import {server} from "../config/index"
import styles from '../styles/Home.module.css'

export default function Home() {
  const [filesSlots, setFileSlots] = useState([0])
  const [files,setFiles] = useState([])
  const [displayResponse,setDisplay] = useState(false)
  function addUploadSlot() {
    let currFilesSlots = filesSlots.slice()
    currFilesSlots.push(0)
    setFileSlots(currFilesSlots)
  }
  function addFiles(data){
    let currFiles = files.slice()
    currFiles.push(data)
    setFiles(currFiles)
  }
  async function postData(data){
    for (var key of data.entries()) {
              console.log(key[0] + ', ' + key[1])
            }
    const response = await fetch(`${server}/api/upload/`,{
      method:'POST',
      mode:'cors',
      body:data, 
    })
    if(response.status!==200){
      let e = await response.json()
      throw new Error(e.error)
     }
    else{
      setDisplay(true)
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.slots}>
      {filesSlots.map((ele,i)=>  <input key={ele.toString()+i} onChange={(e) => {
        addFiles(e.target.files)
        setDisplay(false)
        }} type="file" id="files" name="file" accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" multiple />)}

      </div>
      <button onClick={()=>{
        addUploadSlot()
        setDisplay(false)
        }}>Add More files</button>
      <button onClick={() => {
        const formData = new FormData();
        files.forEach(fileGroup=>{
          Object.values(fileGroup).forEach(ele => {
            formData.append("files", ele)
          })
        })
        postData(formData)
      }} >Upload</button>
        {displayResponse&&<p>Files uploaded succesfully</p>} 
    </div>
  )
}
